### ISSUE TITLE
Moq.AutoMock 3.6.0 generates code with compilation errors

### ISSUE THREAD

**Issue by nil4** [moq/Moq.AutoMocker#402]
After upgrading `Moq.AutoMock` from 3.5.0 to 3.6.0, projects that used to work well now report compiler errors from a source-generated file:

> AutoMockerOptionsExtensions.g.cs(20,78): Error CS0246 : The type or namespace name 'Action<>' could not be found (are you missing a using directive or an assembly reference?)

Reviewing the generated file in the IDE reveals that a couple of namespace `using` statements are likely missing:

<img width="1878" height="928" alt="Image" src="https://github.com/user-attachments/assets/55513fcb-3713-4981-8f01-83c36d768b61" />

To make the generated code compile, it seems that including (at least) `System` and `System.Collections.Generic` around here might be needed:

https://github.com/moq/Moq.AutoMocker/blob/63051e116839cfd2aaf9f046b11e0230ebd9d3c9/Moq.AutoMocker.Generators/OptionsExtensionSourceGenerator.cs#L57-L67
